Repository ThatFrogDev/notabena, pull requests merged in 2023-07, with the labels that each got.

#18 Simpler code and fixed data directory
  .gitignore
  Cargo.lock
  Cargo.toml
  src/api.rs
  src/main.rs
Labels: fork pr's

#20 Bug fixes
  src/api.rs
  src/main.rs
Labels: fork pr's

#19 Fixed multiple issues + convenience
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .gitignore
  Cargo.lock
  Cargo.toml
  src/api.rs
  src/main.rs
Labels: enhancement, todo item

#22 Add Linux installation guide
  README.md
Labels: documentation, maintenance, fork pr's
